# Generated by Django 6.1.1 on 2026-09-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du parent')),
                ('parent_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du parent')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWING', 'En étude'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note administrative')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='classes.schoolclass', verbose_name='Classe demandée')),
            ],
            options={
                'verbose_name': "Demande d'admission",
                'verbose_name_plural': "Demandes d'admission",
                'ordering': ['-created_at'],
            },
        ),
    ]
