services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./backend/.env
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "127.0.0.1,localhost,backend"
      SQLITE_DB_PATH: "/app/data/db.sqlite3"
      CORS_ALLOWED_ORIGINS: "http://localhost,http://127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1"
    ports:
      - "8000:8000"
    volumes:
      - backend_db:/app/data
      - backend_media:/app/media
      - backend_static:/app/staticfiles

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  backend_db:
  backend_media:
  backend_static:
