# Generated by Django 6.1.1 on 2026-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('level', models.CharField(max_length=100, verbose_name='Niveau')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='Capacité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['level', 'name'],
            },
        ),
    ]
